### ISSUE TITLE
SECURITY/FLAWS

### ISSUE THREAD

**Issue by IHATELIFEANDIWANTTODIE** [KadePcGames/Desktop-Remote-Admin-SCP-SL-SMOD-PLUGIN-#2]
This plugin has a lot of good idea but it falls flat on server side security. 

1st default password NO NO NO 
2nd Limit the number of requests sent by 1 IP
3rd "like i said, entirely ignore your UI/clientside stuff
we're talking vulnerabilities so make the assumption that someone has their owned malicious client sending requests to your API
for example
I could write some code that spams random passwords at your login endpoint until it returns true
then I know which password is correct
and I use it in every command request" 
4th
### JUST REMOVE THE PLUGIN!!!!!!!!!!!!

**Comment by Kade-github** [comment]
This was fixed, I assume this was dingo. Everything was updated.
