### ISSUE TITLE
Why in DRA shows only 1 player?

### ISSUE THREAD

**Issue by ITeMbI4** [KadePcGames/Desktop-Remote-Admin-SCP-SL-SMOD-PLUGIN-#3]
![image](https://user-images.githubusercontent.com/46756889/54754858-39c42900-4bed-11e9-9942-3fafa40e988c.png)

**Comment by ITeMbI4** [comment]
![image](https://user-images.githubusercontent.com/46756889/54754806-18fbd380-4bed-11e9-8a3f-8d4502b90785.png)

**Comment by Kade-github** [comment]
This will be fixed in the new version. Thanks for the report!

**Comment by Kade-github** [comment]
Also just noting, I believe you just leaked a bunch of peoples ip's. Lmao...

**Comment by Kade-github** [comment]
This issue was fixed and shall be locked due to it not existing in the new version coming out soon.
