### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by ITeMbI4** [KadePcGames/Desktop-Remote-Admin-SCP-SL-SMOD-PLUGIN-#4]
![image](https://user-images.githubusercontent.com/46756889/54877469-0a4d3080-4e28-11e9-85f4-1ad8096f9117.png)
Ban command doesn't work and maybe make buttons to ban to day, minute or hour?
Next, nuke doesn't start
![image](https://user-images.githubusercontent.com/46756889/54877432-66fc1b80-4e27-11e9-883b-167d8ff4a725.png)
In server console just appear message what nuke started, but it doesn't
![image](https://user-images.githubusercontent.com/46756889/54877440-85faad80-4e27-11e9-87ae-2cfaf5a55e56.png)
And to DRA  can only connect by local IP, not public, port are forwared!

**Comment by ITeMbI4** [comment]
Also, why broadcast and pbc commands time can't be edited and bc is monospaced?

**Comment by Kade-github** [comment]
Weird, during testing all of these worked. I'll do some more testing and try to see if I get the same.

**Comment by Kade-github** [comment]
I'm going to close this because the banning issue was fixed [in this release.](https://github.com/KadePcGames/Desktop-Remote-Admin-SCP-SL-SMOD-PLUGIN-/releases/tag/1.6.1) The nukes, no idea. For me they work.

**Comment by Kade-github** [comment]
`And to DRA can only connect by local IP, not public, port are forwared!` : This is not true either, it's been tested with open ports.
